### ISSUE TITLE
product_enablement image_optimizer changes not applying.

### ISSUE THREAD

**Issue by gruizonestic** [fastly/terraform-provider-fastly#713] opened 2023-06-22 11:14 UTC
### Terraform Version

```shell
Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/fastly/fastly v5.1.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/magodo/restful v0.11.0
```

### Affected Fastly Terraform Resource(s)

- `fastly_service_vcl`

### Terraform Configuration Files

```hcl
module "simple_service" {
  source = "../../"

  fastly_username        = var.fastly_username
  fastly_password        = var.fastly_password
  fastly_api_key         = var.fastly_api_key
  enable_image_optimizer = true
  service_name           = "example.on-dev.com"

  service_domains = [
    {
      service_domain = "example.on-dev.com"
      comment        = "Main domain"
    },
  ]
  service_origins = [
    {
      backend_address = "webservers.example.on-dev.com"
      backend_name    = "Backend name"
      cert_hostname   = "example.on-dev.com"
      sni_hostname    = "example.on-dev.com"
    },
  ]

}
```

And the code from the module itself
```hcl
resource "fastly_service_vcl" "this" {
  name          = var.service_name
  activate      = true
  force_destroy = true
  http3         = var.enable_http3
...
  product_enablement {
    image_optimizer = var.enable_image_optimizer
  }
...
}
```

### Expected Behavior

When changing  `enable_image_optimizer` from `true` to `false` or viceversa, the image optimizer from the `product_enablement` block should be set to change. 

### Actual Behavior

Instead, it returns a 400 Bad Request error.
```sh
module.simple_service.fastly_service_vcl.this: Modifying... [id=sg0wcj6y4hsom7CKeyDFj4]
╷
│ Error: 400 - Bad Request:
│ 
│ 
│   with module.simple_service.fastly_service_vcl.this,
│   on ../../main.tf line 22, in resource "fastly_service_vcl" "this":
│   22: resource "fastly_service_vcl" "this" {
│ 
╵
```
### Steps to Reproduce

1. Create a simple service as described either with the `enable_image_optimizer` variable to `true` or `false` 
2. Apply the changes with `terraform apply`
3. Check that the service is created.
4. Change the `enable_image_optimizer` variable from `true` to `false` or viceversa.
5. Visualize the changes with a `terraform plan` 
```sh
 # module.simple_service.fastly_service_vcl.this will be updated in-place
  ~ resource "fastly_service_vcl" "this" {
      ~ active_version     = 1 -> (known after apply)
      ~ cloned_version     = 1 -> (known after apply)
        id                 = "..."
        name               = "example.on-dev.com"
        # (9 unchanged attributes hidden)

      - product_enablement {
          - brotli_compression = false -> null
          - domain_inspector   = false -> null
          - image_optimizer    = false -> null
          - name               = "products" -> null
          - origin_inspector   = false -> null
          - websockets         = false -> null
        }
      + product_enablement {
          + brotli_compression = false
          + domain_inspector   = false
          + image_optimizer    = true
          + name               = (known after apply)
          + origin_inspector   = false
          + websockets         = false
        }

        # (6 unchanged blocks hidden)
    }
```
6. Run the changes with `terraform apply`
7. It returns an error 400 Bad-Request.

### Important Factoids (optional)

Is there anything atypical about your account or set up that we should know? 
No.

**Comment by Integralist** [comment] 2023-06-23 10:46
Hi @gruizonestic 

Thank you for opening this issue.

## Summary

I _think_ you need to do two things:

1. Remove `product_enablement` from your config, add a `shield` attribute to your `backend` block, then run `terraform apply`.
2. Add back in the `product_enablement` block into your config, and again run `terraform apply`.

## Longer explanation

I was able to create a reduced test case to see the error you're seeing. 

The steps I took were slightly different to yours, but actually resulted in me discovering an interesting side-effect, which I'll explain in a bit.

So firstly what I did differently was I initially ran (successfully) `terraform apply` with just a `fastly_service_vcl` configured, and no `product_enablement` defined in my service config (I also had a `backend` defined but it had _no_ `shield` attribute set).

After the first `terraform apply` ran successfully (and consequently I had a new service created, and activated at service version 1) I then added the `product_enablement` block to my config (with `image_optimizer = true`) and as you rightly reported there is an error returned, but it's not clear what actually went wrong.

So first thing I did was figure out what the error was. To do this I manually `curl`ed the [Product Enablement API endpoint](https://developer.fastly.com/reference/api/products/enablement/#enable-product) and this revealed that I had a backend which was missing a `shield` setting.

I then investigated why I wasn't seeing that error in Terraform, and traced it back to a bug in the go-fastly API client ([here's a PR fixing the issue](https://github.com/fastly/go-fastly/pull/449)) and I've now released a new go-fastly version with the fix ([`v8.5.2`](https://github.com/fastly/go-fastly/releases/tag/v8.5.2)).

At this point I still need to publish a new Terraform provider release that _uses_ this new go-fastly version, so that in future, errors should be displayed properly. But for now, in order to get my `terraform apply` to succeed I knew I needed to add a `shield` attribute to my `backend` block.

It does actually state this in the Terraform docs:
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#nestedblock--product_enablement

> `image_optimizer` (Boolean) Enable Image Optimizer support (requires at least one backend with a `shield` attribute).

But here's where, for me at least, I was still running into issues. Turns out the backend needs to exist, with the shield set, in an 'active' service version first. 

This is because of how the Terraform provider is architected. 

What happens when there's a change to the `fastly_service_vcl` resource, is the provider will first clone the service (so you have a new draft/inactive service version), it then makes any changes and finally 'activates' the service. 

The problem is that when you make a `backend` change (e.g. add the `shield` setting), the Terraform provider will call the `product_enablement` API (to enable the product) _before_ activating the service. This is because the `product_enablement` block is defined _within_ the `fastly_service_vcl` resource.

So for me to get it working I had to first temporarily delete the `product_enablement` block from my config, make sure my `backend` block has a `shield` set, then run `terraform apply`. Next, I have to add the `product_enablement` block back into my config and run a second `terraform apply`.

Now you don't need a two-step apply if you're creating a new service for the first time (e.g. you have no service created yet). You can define your service, with a backend with a shield, _and_ define the `product_enablement` block and the `terraform apply` will succeed. 

The reason for this is that the API, when given the Service ID, looks for an active service version to check against and if it finds one it looks at its backend settings. If there is no active version, such as the case in a scenario I've described where you're creating a new service at the same time, then it will check for the latest draft/inactive service version and check the backend object there, whereupon it finds the service version the Terraform provider has just created, and so the backend in that draft does have a shield set.

I'm going to publish a new Terraform release shortly to include the updated go-fastly API client. This should help others in future as there should now be a better error message displayed.

Let me how you get on with the two-step apply approach.

Thanks!

**Comment by gruizonestic** [comment] 2023-06-26 06:53
Hi @Integralist,

Thanks for your detailed explanation. I really appreciate it. I've tried doing steps one and two, but the issue still remains. When I create the service, whether it has the `shield` option enabled or not, I still cannot activate the image optimizer. The only way I can do it is by activating it at the creation of the service (with shielding on). After the initial creation of the service, no matter the shielding or the active configuration of the service, it always returns a `400 Bad Request` error. The only workaround I could found is enabling image optimizer through Fastly's web UI.

**Comment by Integralist** [comment] 2023-06-26 16:02
@gruizonestic 

Oh interesting.

So I just tried with a new project...

```tf
terraform {
  required_providers {
    fastly = {
      source  = "fastly/fastly"
      version = "5.1.0"
    }
  }
}

resource "fastly_service_vcl" "demo" {
  name = "testing-fastly-tf-prod-enablement-bug"

  domain {
    name = "testing-fastly-tf-prod-enablement-bug.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
    shield  = "amsterdam-nl"
  }

  product_enablement {
    image_optimizer = true
  }

  force_destroy = true
}
```

And this applied fine for me...

```
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be created
  + resource "fastly_service_vcl" "demo" {
      + activate           = true
      + active_version     = (known after apply)
      + cloned_version     = (known after apply)
      + comment            = "Managed by Terraform"
      + default_ttl        = 3600
      + force_destroy      = true
      + force_refresh      = (known after apply)
      + http3              = false
      + id                 = (known after apply)
      + imported           = (known after apply)
      + name               = "testing-fastly-tf-prod-enablement-bug"
      + stale_if_error     = false
      + stale_if_error_ttl = 43200

      + backend {
          + address               = "127.0.0.1"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 1000
          + error_threshold       = 0
          + first_byte_timeout    = 15000
          + max_conn              = 200
          + name                  = "localhost"
          + port                  = 80
          + shield                = "amsterdam-nl"
          + ssl_check_cert        = true
          + use_ssl               = false
          + weight                = 100
        }

      + domain {
          + name = "testing-fastly-tf-prod-enablement-bug.integralist.co.uk"
        }

      + product_enablement {
          + brotli_compression = false
          + domain_inspector   = false
          + image_optimizer    = true
          + name               = (known after apply)
          + origin_inspector   = false
          + websockets         = false
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
fastly_service_vcl.demo: Creating...
fastly_service_vcl.demo: Creation complete after 7s [id=blgln4pflDDIwMDDjC0xe6]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Then running a second plan to check all is fine:

```
$ terraform plan

fastly_service_vcl.demo: Refreshing state... [id=blgln4pflDDIwMDDjC0xe6]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Comment by gruizonestic** [comment] 2023-06-27 06:26
Hi @Integralist,
That is the only way I can enable image optimizer. Creating a service for the first time with a shielded backend and image optimizer enabled. 

Try to do the following:
1. After creating the "demo" service, put `image_optimizer` to `false`.
2. Run `terraform apply` again. 

It will show you an error trying to disable it. That's not the expected behaviour, right? 

Thanks for the research :)

**Comment by Integralist** [comment] 2023-06-27 09:33
Hmm, interesting. I'm not seeing that using the same provider version as you (5.1.0).

I'll quickly demonstrate what I'm seeing and then I'll make some suggestions for next steps. 

## What I'm seeing

First I create the service with a backend that has a `shield` property set...

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be created
  + resource "fastly_service_vcl" "demo" {
      + activate           = true
      + active_version     = (known after apply)
      + cloned_version     = (known after apply)
      + comment            = "Managed by Terraform"
      + default_ttl        = 3600
      + force_destroy      = true
      + force_refresh      = (known after apply)
      + http3              = false
      + id                 = (known after apply)
      + imported           = (known after apply)
      + name               = "testing-fastly-tf-prod-enablement-bug"
      + stale_if_error     = false
      + stale_if_error_ttl = 43200

      + backend {
          + address               = "127.0.0.1"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 1000
          + error_threshold       = 0
          + first_byte_timeout    = 15000
          + max_conn              = 200
          + name                  = "localhost"
          + port                  = 80
          + shield                = "amsterdam-nl"
          + ssl_check_cert        = true
          + use_ssl               = false
          + weight                = 100
        }

      + domain {
          + name = "testing-fastly-tf-prod-enablement-bug.integralist.co.uk"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fastly_service_vcl.demo: Creating...
fastly_service_vcl.demo: Creation complete after 5s [id=SHk30ejeCHZbFUwSUhJPs4]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I then add the `product_enablement` block with `image_optimizer = true` and that applies fine...

```
fastly_service_vcl.demo: Refreshing state... [id=SHk30ejeCHZbFUwSUhJPs4]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be updated in-place
  ~ resource "fastly_service_vcl" "demo" {
      ~ active_version     = 1 -> (known after apply)
      ~ cloned_version     = 1 -> (known after apply)
        id                 = "SHk30ejeCHZbFUwSUhJPs4"
        name               = "testing-fastly-tf-prod-enablement-bug"
        # (9 unchanged attributes hidden)

      + product_enablement {
          + brotli_compression = false
          + domain_inspector   = false
          + image_optimizer    = true
          + name               = (known after apply)
          + origin_inspector   = false
          + websockets         = false
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fastly_service_vcl.demo: Modifying... [id=SHk30ejeCHZbFUwSUhJPs4]
fastly_service_vcl.demo: Still modifying... [id=SHk30ejeCHZbFUwSUhJPs4, 10s elapsed]
fastly_service_vcl.demo: Modifications complete after 12s [id=SHk30ejeCHZbFUwSUhJPs4]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Then lastly I set `image_optimizer = false` which applies successfully...

```
fastly_service_vcl.demo: Refreshing state... [id=SHk30ejeCHZbFUwSUhJPs4]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be updated in-place
  ~ resource "fastly_service_vcl" "demo" {
      ~ active_version     = 2 -> (known after apply)
      ~ cloned_version     = 2 -> (known after apply)
        id                 = "SHk30ejeCHZbFUwSUhJPs4"
        name               = "testing-fastly-tf-prod-enablement-bug"
        # (9 unchanged attributes hidden)

      + product_enablement {
          + brotli_compression = false
          + domain_inspector   = false
          + image_optimizer    = false
          + name               = (known after apply)
          + origin_inspector   = false
          + websockets         = false
        }
      - product_enablement {
          - brotli_compression = false -> null
          - domain_inspector   = false -> null
          - image_optimizer    = true -> null
          - name               = "products" -> null
          - origin_inspector   = false -> null
          - websockets         = false -> null
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fastly_service_vcl.demo: Modifying... [id=SHk30ejeCHZbFUwSUhJPs4]
fastly_service_vcl.demo: Still modifying... [id=SHk30ejeCHZbFUwSUhJPs4, 10s elapsed]
fastly_service_vcl.demo: Modifications complete after 15s [id=SHk30ejeCHZbFUwSUhJPs4]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

## Next steps

First I would recommend upgrading to https://github.com/fastly/terraform-provider-fastly/releases/tag/v5.2.1 as that version of the provider uses the updated go-fastly API client that should hopefully return better error information. Then when you run `terraform apply` prefix that with `TF_LOG=DEBUG` as that will show all the API calls the provider makes. 

I'd like to see the request/response for the API call that's disabling the Image Optimizer.

After that, I would recommend reaching out to support@fastly.com (or via Slack if you have access to a Fastly support Slack channel) and to reference this issue, as they'll be able to check your account access and see if there are any limitations/restrictions in place. 

But let's first see what log output you're getting back.

Thanks!

**Comment by gruizonestic** [comment] 2023-06-27 11:01
Hi again @Integralist,

I'm glad to tell you that the error is no longer happening on Fastly's provider version `v5.2.1`. I can now enable and disable the `image_optimizer` without problems. I didn't change anything or made any different steps as what I previously stated. Only change was from upgrading the provider from `v5.1.0` to `v5.2.1`. 

Thanks for taking your time and helping me tracking the issue. Is there anything else I can do for you? Perhaps you still want to check some logs?

Thanks!

**Comment by Integralist** [comment] 2023-06-27 11:23
Hmm, very strange that the upgrade helped you as I don't see anything in the intermediary releases that would have changed anything in the product_enablement area but I'm glad it's working for you 🙂

I'm going to close this issue for now. But feel free to reach out again if there are any other issues.

**Closed as completed by Integralist** 2023-06-27 11:23 UTC
