### ISSUE TITLE
ensure `ssl_cert_hostname` present when `ssl_check_cert = "true"`

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#431] opened 2021-06-23 17:12 UTC
### Problem

I have found an interesting issue when we introduced a misconfigured new backend, it got the new configuration created as draft, and shows error message as below:

```
Mandatory SSL cert checks require specifying cert hostname
at: (input Line 23 Pos 6)
    .ssl_check_cert = always;
-----##############----------
```

That actually blocks all subsequent changes with something like `Detail: Duplicate backend: 'new_backend`. In other words, commit reverts do not help at all.

### Workaround

I have re-import the state to reset the tfstate to be able to workaround this issue.

### Terraform Version

terraform 1.0.0
provider 0.30.0 and 0.28.2

### Affected Resource(s)
Please list the resources as a list, for example:
- `fastly_service_v1`

**Comment by smaeda-ks** [comment] 2021-06-26 17:09
FYI, this was recently fixed in https://github.com/fastly/terraform-provider-fastly/pull/418
and @chenrui333 kindly confirmed that the issue is fixed in the latest version. Thanks for your report.

This issue can be closed.

**Comment by Integralist** [comment] 2021-06-28 08:06
Thanks @smaeda-ks 👍🏻 ❤️

**Closed as completed by Integralist** 2021-06-28 08:06 UTC
