### ISSUE TITLE
Domains do not support count, making variable interpolation impossible 

### ISSUE THREAD

**Issue by brennentsmith** [fastly/terraform-provider-fastly#69] opened 2018-02-14 00:55 UTC
### Terraform Version
Terraform v0.11.2
+ provider.fastly v0.1.4

### Affected Resource(s)
- domain 

Currently the Domain field does not support `count`, which makes variable interpolation very difficult. Our goal is to be able to specify a map of domains, depending on the environment (staging/prod), and retain the same config between both envs. Since domains does not include count, it's rather difficult to perform this, as domains have to be specified explicitly, thus making the Fastly config non-reusuable. 

An attempt at this would be:
```

resource "fastly_service_v1" "demo" {
  name = "demofastly"

  domain {
    name    = "${element(split(",", var.domains["domain"]), count.index)}"
    comment = "${element(split(",", var.domains["comment"]), count.index)}"
    count = "${length(var.domains)}"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  force_destroy = true
}
```

See https://www.terraform.io/docs/configuration/resources.html#using-variables-with-count.

If anyone has any advice on a different method to have a single (or identical) config between staging and prod (two Fastly environments), just different listening domains, we would love it!

**Comment by msuterski** [comment] 2018-02-16 21:58
We've solved it with a separate build step in our pipeline. 

We're using `gomplate` and template the .tf files and put something like this in them
```
{{ $domains := (datasource "config").domains }}{{range $domains }}
  domain = { name = "{{.}}" }
{{- end}}
```
The steps would be something like

1. `/gomplate -f fastly.tf.tmpl -o fastly.tf -d config=config/dev.yml`
1. `terraform plan ...`

**Comment by msuterski** [comment] 2018-02-21 17:47
this issue is a duplicate of https://github.com/terraform-providers/terraform-provider-fastly/issues/2

**Comment by wosc** [comment] 2019-02-13 12:23
The same problem (no `count` support) also applies to... basically all the fastly resources, AFAICT. Which is rather limiting, here are some use cases:

* We want to _not_ configure logging (bigquerylogging/gcslogging) for our staging system, but as I understand it, `count` is the only way to achieve an effect like `if terraform.workspace == "production"` with terraform.
(For this concrete problem I'm going to try a workaround with a `condition` on the logging resource that always evaluates to false in staging, but that feels rather clumsy.)
* We have three `backend` servers for our service, whose configuration (which is quite lengthy, with SSL certificates etc.) is exactly the same, except for the hostname. It would be nice if we didn't have to copy&paste all of it three times.

**Comment by chadgrant** [comment] 2019-03-28 04:36
why not just allow a csv value in for now until terraform properly supports count?

**Comment by samirspatel** [comment] 2019-03-29 02:47
We would really like for this to be implemented we we use a large list of domains and it is becoming very unwieldy to maintain

**Comment by matthope** [comment] 2019-08-07 13:10
Could you do something like...

```
  dynamic "domain" {
    for_each = var.domains
    content {
      name = "${domain.value}"
    }
  }
```

with

```
variable "domains" {
  type = list(string)
  default = [ "localhost" ]
}
```


?

**Comment by smaeda-ks** [comment] 2021-09-15 10:58
Yes, this shouldn't be a blocker these days. Please consider using dynamic blocks.
https://www.terraform.io/docs/language/expressions/dynamic-blocks.html

https://github.com/fastly/terraform-provider-fastly/issues/2#issuecomment-881805372

Closing this issue.

**Closed as completed by smaeda-ks** 2021-09-15 10:58 UTC
Labels: enhancement, upstream-terraform
