### ISSUE TITLE
Setting a header is failing with error

### ISSUE THREAD

**Issue by zefrs** [fastly/terraform-provider-fastly#650] opened 2023-02-28 20:25 UTC
### Terraform Version
Terraform v1.3.0
on darwin_arm64

### Affected Resource(s)
"fastly_service_vcl" 

### Terraform Configuration Files
```hcl
  header {
      action      = "set"
      destination = "http.x-cdn-name"
      name        = "x-cdn-name"
      type        = "cache"
      source      = "fastly"
    }
```

### Debug Output
╷
│ Error: invalid configuration for Fastly Service (EtQxwH1vaVosUNOQf23YX5): Syntax error: Expected string variable or constant
│ at: (input Line 118 Pos 38)
│         set beresp.http.x-cdn-name = fastly;
│ -------------------------------------######-
│ 
│   with fastly_service_vcl.terraform89966,
│   on main.tf line 41, in resource "fastly_service_vcl" "terraform89966":
│   41: resource "fastly_service_vcl" "terraform89966" {
│ 
╵

### Expected Behavior
Terraform successfully ran and added a header

### Actual Behavior
Adding a header fails with the above error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

when trying to set a header it errors stating that `action      = "set"` should be a string or constant.

**Comment by Integralist** [comment] 2023-03-09 12:20
Hi @zefrs 👋🏻 

Thanks for opening this issue. I believe what you're experiencing is expected behaviour. 

So let me go into more detail about why that is...

The error is caused by you specifying a value that is not a Varnish/VCL _variable_.

If you look at the generated VCL code (shown in the error):

```vcl
set beresp.http.x-cdn-name = fastly;
```

The value assigned to the header is not a string `"fastly"` but a literal `fastly` which means Varnish is expecting to find a `fastly` _variable_ defined.

The [documentation states](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#source):

> Variable to be used as a source for the header content

If we check the [API example for creating a header](https://developer.fastly.com/reference/api/vcl-services/header/#create-header-object), we can see:

> `src=client.ip`

Which confirms the value expected is a VCL variable.

Here are all the variables currently exposed:
https://developer.fastly.com/reference/vcl/variables/

You'll need to select a variable that is valid for the Varnish subroutine the header is being added to (i.e. the `type` attribute).

I'm going to close this issue now, but feel free to continue the discussion if you have any further questions.

Thanks!

**Closed as completed by Integralist** 2023-03-09 12:20 UTC
