### ISSUE TITLE
Unable to Create a Dictionary with Items from one Terraform Apply

### ISSUE THREAD

**Issue by rcollier-goodrx** [fastly/terraform-provider-fastly#228] opened 2020-04-30 19:04 UTC
Hi,

I'm following the example docs [here](https://www.terraform.io/docs/providers/fastly/r/service_dictionary_items_v1.html) to create a dictionary and items in that dictionary. When I run terraform apply, terraform fails to create the dictionary and populate it with items. 

It throws this error:

```
Error: Invalid index

  on .terraform/modules/fastly.fastly-service/dictionary_items.tf line 17, in resource "fastly_service_dictionary_items_v1" "items":
  17:   dictionary_id = "${ { for s in fastly_service_v1.cdn.dictionary : s.name => s.dictionary_id }[var.mydict_name]}"
    |----------------
    | fastly_service_v1.cdn.dictionary is set of object with 2 elements
    | var.mydict_name is "My Dictionary"

The given key does not identify an element in this collection value.

Releasing state lock. This may take a few moments...
```

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1.cdn.dictionary
- fastly_service_dictionary_items_v1

### Terraform Configuration Files
The code I am using can be found in the example [here](https://www.terraform.io/docs/providers/fastly/r/service_dictionary_items_v1.html#example-usage)

### Expected Behavior
The creation of a dictionary filled with items from a single terraform apply.

### Actual Behavior
Terraform failed to create both the dictionary and the items. To resolve this I had to comment out the fastly_service_dictionary_items_v1 resource and run two terraform apply's. 

1. To create the dictionary
2. To populate the dictionary with items

This isn't really a problem when having to import pre-existing services into fastly, but it's not a good experience for creating a new service that is managed by terraform from the beginning.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Copy the example code that I linked to above.
2. Run `terraform apply` and witness the failure.
3. Comment out the `fastly_service_dictionary_items_v1` resource, run `terraform apply` again to create the dictionary.
4. Uncomment the `fastly_service_dictionary_items_v1` resource, run `terraform apply` again to populate the dictionary with items.

**Comment by phamann** [comment] 2020-04-30 19:28
@rcollier-goodrx thank you for the report. This is the expected behaviour of these resources, due to the way they were designed the constraints by the Fastly API and Terraform SDK.

The `fastly_service_dictionary_items_v1` needs a reference to the `dictionary` container on the `fastly_service_v1` resource so it can get the dictionary ID during creation, the dictionary ID is required by the Fastly API when you are creating items. Therefore, you must first provision container, and thus persist it to the statefile, before creating an items resource.

I do however agree that it's not a nice UX for adding new dictionaries, so will make sure we update the docs to detail this nuance. However, I'm going to close this issue as we cannot change the behaviour.

**Closed as completed by phamann** 2020-04-30 19:28 UTC

**Comment by rcollier-goodrx** [comment] 2020-04-30 20:43
@phamann thank you for responding. I had a feeling that was the case, but I appreciate your explanation nonetheless.

**Comment by rcollier-goodrx** [comment] 2020-04-30 21:33
This behavior extends to other resources such as ACLs as well, please make sure to update the documentation for that as well. Thanks!

**Comment by elliterate** [comment] 2020-09-09 20:51
> The `fastly_service_dictionary_items_v1` needs a reference to the `dictionary` container on the `fastly_service_v1` resource so it can get the dictionary ID during creation, the dictionary ID is required by the Fastly API when you are creating items. Therefore, you must first provision container, and thus persist it to the statefile, before creating an items resource.

@phamann What about the Terraform SDK prevents you from doing this in a single `apply`? If one resource depends on a property of another resource, Terraform should process the dependent resource first and provide the property's value (e.g., the dictionary's `id`) without requiring an intermediate `apply`. (If this is a limitation of nested resources/blocks, couldn't Fastly just implement a first-class `dictionary` resource?)

**Comment by phamann** [comment] 2020-09-30 11:06
Hi all (@rcollier-goodrx, @elliterate). A very delayed update on issue - which I personally apologise for, as my initial response was incorrect. This issue - and other similar reports - prompted us to do some further analysis into the underlying problem and work out why it is happening. Fortunately, there is a confirmed workaround :tada:

**TL;DR**
We have determined that this is a bug with the way Terraform evaluates _Computed_ attributes inside `Sets`, we have since reported the problem [upstream](https://github.com/hashicorp/terraform/issues/26419) to HashiCorp and have found a workaround which resolves the problem using the new `for_each` syntax,  lastly we have updated our documentation for these resources with the workaround.

For a detailed explanation see the documentation PR #324 and associated Terraform [issue](https://github.com/hashicorp/terraform/issues/26419). However, please let us know in this thread if the suggested solution resolves your problem or you find any other related issues 😄  

For those interested, here is a more detailed explanation taken from #324:

---

In order to use _versionless_ resources (i.e. ACL Entries, Dictionary Items, Dynamic Snippets Content), it's required to link the ID generated from the Fastly Service (`fastly_service_v1`) to the respective field in the _versionless_ resource (i.e `fastly_service_acl_entries`, `fastly_service_dictionary_items_v1`, `fastly_service_dynamic_snippet_content_v1`).

The original documentation instructed to the use of _for expressions_ to create this link. For example:

``` 
resource "fastly_service_v1" "myservice" {
  ...
  dictionary {
    name = "dict1"
  }

}
resource "fastly_service_dictionary_items_v1" "items" {
  service_id = fastly_service_v1.myservice.id
  dictionary_id = {for d in fastly_service_v1.myservice.dictionary : d.name => d.dictionary_id}["dict1"]
  ...
}
```

This seems to work for many scenarios, however, not for all. 
It fails mainly when the resource `fastly_service_v1` already exists and we add the `acl` block at the same time, we add `fastly_service_acl_entries` resources (The same occur for the other _versionless_ resources).

The generated error is: `Error: Invalid index`

This seems to be due to the way Terraform evaluates *Computed* attributes inside `Sets`. When the resource doesn't exist, Terraform postpones the evaluation of the expression as the values are [not yet known](https://www.terraform.io/docs/configuration/expressions.html%23values-not-yet-known).
However, when the resource exists and the  Set attribute is being modified, Terraform tries to evaluate the expression before the all values are known causing the error. This is likely to be an issue in Terraform.

When replacing the _for expression_ with a `for_each` attribute, Terraform is able to resolve the values correctly. That is, Terraform detects that a value the computed id is still not available and postpones the expression evaluation. 

Interestingly enough, if using the _for expression_ with an `if` and `lookup`, the issue seems to also disappear. For example

```
lookup​({​for​ ​d​ in ​fastly_service_v1​.myservice.dictionary : ​d​.​name​ ​=>​ ​d​.dictionary_id ​if​ ​d​.​name == "dict1"​}, "dict1", ​""​)
```
This approach however is not as clean as the `for_each` one.

For all those reasons, the documentation was updated to recommend the `for_each` approach.

A similar issue also happens to `List` types and current affects the WAF resource. (This issue was previously raised against Terraform - see https://github.com/hashicorp/terraform/issues/23488)
